package com.travel.hub.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AgencyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgencyAllPropertiesEquals(Agency expected, Agency actual) {
        assertAgencyAutoGeneratedPropertiesEquals(expected, actual);
        assertAgencyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgencyAllUpdatablePropertiesEquals(Agency expected, Agency actual) {
        assertAgencyUpdatableFieldsEquals(expected, actual);
        assertAgencyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the derived primary key is set correctly.
     *
     * @param entityToPersist the entity used to persist
     * @param persisted the persisted entity
     */
    public static void assertAgencyMapsIdRelationshipPersistedValue(Agency entityToPersist, Agency persisted) {
        // Validate the id for MapsId, the ids must be same
        assertThat(entityToPersist.getUser_agency().getId()).isEqualTo(persisted.getId());
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgencyAutoGeneratedPropertiesEquals(Agency expected, Agency actual) {
        assertThat(actual)
            .as("Verify Agency auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgencyUpdatableFieldsEquals(Agency expected, Agency actual) {
        assertThat(actual)
            .as("Verify Agency relevant properties")
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getAddress()).as("check address").isEqualTo(expected.getAddress()))
            .satisfies(a -> assertThat(a.getWebsite()).as("check website").isEqualTo(expected.getWebsite()))
            .satisfies(a -> assertThat(a.getRatingAvg()).as("check ratingAvg").isEqualTo(expected.getRatingAvg()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgencyUpdatableRelationshipsEquals(Agency expected, Agency actual) {
        // empty method
    }
}
